# Generated by Django 2.2.4 on 2019-08-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects_hours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personsubject',
            name='typology',
        ),
        migrations.AddField(
            model_name='subject',
            name='typology',
            field=models.CharField(default='', max_length=1),
        ),
    ]
