# Generated by Django 2.2.4 on 2019-09-04 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects_hours', '0002_auto_20190829_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='personsubject',
            name='date',
            field=models.DateField(default=datetime.date(2019, 9, 4)),
        ),
        migrations.AlterUniqueTogether(
            name='personsubject',
            unique_together=set(),
        ),
    ]
