# Generated by Django 2.2.4 on 2019-09-24 21:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subjects_hours', '0003_auto_20190904_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_person', models.CharField(max_length=20)),
                ('group', models.CharField(default='1', max_length=3)),
                ('period', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedication_hours', models.IntegerField()),
                ('autonomous_hours', models.IntegerField()),
                ('accompaniment_hours', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects_hours.PersonSchedule')),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='typology',
        ),
        migrations.DeleteModel(
            name='PersonSubject',
        ),
        migrations.AddField(
            model_name='personschedule',
            name='cod_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects_hours.Subject'),
        ),
    ]
